name: "mapingway-node"

services:
  app:
    container_name: "api"
    build:
      context: ../
      dockerfile: /docker/app/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      # Do not create development certificate in an environment that will be distributed.
      - ASPNETCORE_Kestrel__Certificates__Default__Password=sfhhsSKKntupO6O
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Mapingway.API.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
  db:
    container_name: "database"
    build:
      context: ../
      dockerfile: /docker/localdb/Dockerfile