name: "Develop: Publish on Push"

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Calculate Image Version
      uses: PaulHatch/semantic-version@v5.3.0
      id: meta
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        change_path: "src/"
        namespace: burn1n9/mapingway
        search_commit_body: true
        debug: true

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: .docker/app/Dockerfile
        push: true
        tags: burn1n9/mapingway:${{ steps.meta.outputs.version }}
        # use layer caching. Don't forget mode=max to also cache the build image
        # (vs only the final image - mode: min)
        ##cache-from: type=gha
        ##cache-to: type=gha,mode=max