name: "Develop: Publish on Push"

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Calculate Image Version
      uses: PaulHatch/semantic-version@v5.3.0
      id: meta
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}-development.${increment}"
        change_path: "src/"
        namespace: burn1n9/mapingway
        search_commit_body: true


    - name: Prepare Buildx
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        IMAGE="registry.hub.docker.com/burn1n9/mapingway"
        echo ::set-output name=tagged_image::${IMAGE}:${TAG}
        echo ::set-output name=tag::${TAG}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    
    # Registry login step intentionally missing

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-single-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-single-buildx
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: .docker/app/Dockerfile
        push: true
        tags: burn1n9/mapingway:${{ steps.meta.outputs.version }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
      
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        
    - name: Tag Current Commit with version
      uses: anothrNick/github-tag-action@1.67.0 
      env:
        CUSTOM_TAG: ${{ steps.meta.outputs.version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}